# permissions for end users to view logprojects.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: logproject-viewer-role
rules:
- apiGroups:
  - logservice.hsc.philips.com.cn
  resources:
  - logprojects
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - logservice.hsc.philips.com.cn
  resources:
  - logprojects/status
  verbs:
  - get
